# Generated by Django 2.2.2 on 2019-06-14 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='url',
            new_name='domain',
        ),
    ]
