# Generated by Django 2.2.2 on 2019-06-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='secondary_url',
            field=models.TextField(blank=True),
        ),
    ]
